// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYazu-DrdhOShvebvE0zJE5iK-vqSVHsA',
    appId: '1:448065783615:web:2b2d43dc37f7d8efe7f58a',
    messagingSenderId: '448065783615',
    projectId: 'circle-c9110',
    authDomain: 'circle-c9110.firebaseapp.com',
    storageBucket: 'circle-c9110.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRB1YV9zfOtRu2VXm16Zms6lzodlP1m2Y',
    appId: '1:448065783615:android:81c8b4069272d52ce7f58a',
    messagingSenderId: '448065783615',
    projectId: 'circle-c9110',
    storageBucket: 'circle-c9110.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbn2Vmpd3fiXQLbvlpL68Qdad4UnzVIsw',
    appId: '1:448065783615:ios:857b66a2b447b1f9e7f58a',
    messagingSenderId: '448065783615',
    projectId: 'circle-c9110',
    storageBucket: 'circle-c9110.appspot.com',
    iosClientId: '448065783615-4gjv8vu0c7i78flei42p1i86b5hn810v.apps.googleusercontent.com',
    iosBundleId: 'com.example.circle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbn2Vmpd3fiXQLbvlpL68Qdad4UnzVIsw',
    appId: '1:448065783615:ios:857b66a2b447b1f9e7f58a',
    messagingSenderId: '448065783615',
    projectId: 'circle-c9110',
    storageBucket: 'circle-c9110.appspot.com',
    iosClientId: '448065783615-4gjv8vu0c7i78flei42p1i86b5hn810v.apps.googleusercontent.com',
    iosBundleId: 'com.example.circle',
  );
}
